"""
DataLoader for Chromosome-wise uint8 format GWAS data
WITH DISEASE-SPECIFIC GWAS FILTERING ONLY

Simplified version that ONLY supports disease-specific GWAS filtering.
Requires filtered indices from ukbb_gwas_position_only_matching_final.py

Features:
- Disease-specific GWAS filtering (REQUIRED)
- Rotation-based control subsampling for class imbalance
- Memory-efficient chunked loading
- FAST SNP filtering using precomputed indices

Usage:
    # MUST specify disease for GWAS filtering
    dataloaders = create_dataloaders_with_rotation(
        ...,
        disease_for_snp_filter='t2d',  # REQUIRED: 't2d', 'prostate', 'breast', 'colon', 'pancreatic'
        ...
    )
"""

import os
import pandas as pd
import torch
import numpy as np
from torch.utils.data import Dataset, DataLoader
import glob
import time
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler, QuantileTransformer, PowerTransformer


# Directory paths for chromosomes
BASE_PATH = "/mnt/fast/datasets/ucdatasets/gwas/ukbb/samples_chr_wise_uint8"

# GWAS-filtered SNPs directory (output from ukbb_gwas_position_only_matching_final.py)
GWAS_FILTERED_SNPS_PATH = "/mnt/fast/datasets/ucdatasets/gwas/ukbb/samples_chr_wise_uint8/snvs_summ_stats_filtered_0.1/gwas_filtered"

# Phenotype file path
PHENOTYPE_FILE = "/mnt/fast/datasets/ucdatasets/gwas/ukbb/samples_chr_wise_uint8/ukb_cancers_t2d_ukb676869_13102025_cleaned_matched.tsv"

# Available diseases for GWAS filtering
AVAILABLE_GWAS_DISEASES = ['t2d', 'prostate', 'breast', 'colon', 'pancreatic']


# Global cache for GWAS filtered indices (loaded once from disk)
_GWAS_FILTERED_INDICES_CACHE = {}


def load_gwas_filtered_indices(chr_num, disease=None, gwas_filtered_path=GWAS_FILTERED_SNPS_PATH, rank=0):
    """
    Load disease-specific GWAS-filtered SNP indices from disk
    (generated by ukbb_gwas_position_only_matching_final.py)
    
    Args:
        chr_num: Chromosome number (1-22)
        disease: Disease key ('t2d', 'prostate', 'breast', 'colon', 'pancreatic')
                 If None, returns None (no filtering - load all SNPs)
        gwas_filtered_path: Base directory for GWAS-filtered SNPs
        rank: Process rank for distributed training (default 0)
    
    Returns:
        numpy array of indices to keep, or None if no filtering requested
    
    Raises:
        FileNotFoundError: If filtered indices file doesn't exist (when disease is specified)
        ValueError: If disease is invalid
    """
    # No filtering requested
    if disease is None:
        if rank == 0:
            print(f"  Chr{chr_num}: No filtering - loading ALL SNPs")
        return None
    
    # Validate disease
    if disease not in AVAILABLE_GWAS_DISEASES:
        raise ValueError(
            f"Invalid disease '{disease}'. "
            f"Available diseases: {AVAILABLE_GWAS_DISEASES}"
        )
    
    # Create cache key
    cache_key = f'chr{chr_num}_{disease}_gwas'
    
    # Check if already loaded in cache
    if cache_key in _GWAS_FILTERED_INDICES_CACHE:
        return _GWAS_FILTERED_INDICES_CACHE[cache_key]
    
    # Path to disease-specific filtered indices
    disease_chr_dir = os.path.join(gwas_filtered_path, disease, f"chr{chr_num}")

    # # Try to load indices
    # npy_file = os.path.join(disease_chr_dir, f"chr{chr_num}_filtered_indices_{disease}.npy")
    # txt_file = os.path.join(disease_chr_dir, f"chr{chr_num}_filtered_indices_{disease}.txt")
    
    # Try to load indices
    npy_file = os.path.join(disease_chr_dir, f"chr{chr_num}_snvs_summ_stats_filtered_indices_{disease}.npy")
    txt_file = os.path.join(disease_chr_dir, f"chr{chr_num}_snvs_summ_stats_filtered_indices_{disease}.txt")

    if os.path.exists(npy_file):
        if rank == 0:
            print(f"  Loading GWAS-filtered indices for chr{chr_num}, disease={disease}")
        indices = np.load(npy_file)
        _GWAS_FILTERED_INDICES_CACHE[cache_key] = indices
        if rank == 0:
            print(f"    Loaded {len(indices):,} GWAS-filtered SNP indices")
        return indices
    elif os.path.exists(txt_file):
        if rank == 0:
            print(f"  Loading GWAS-filtered indices for chr{chr_num}, disease={disease} from text...")
        indices = np.loadtxt(txt_file, dtype=np.int64)
        _GWAS_FILTERED_INDICES_CACHE[cache_key] = indices
        if rank == 0:
            print(f"    Loaded {len(indices):,} GWAS-filtered SNP indices")
        return indices
    else:
        raise FileNotFoundError(
            f"GWAS-filtered indices not found for chr{chr_num}, disease={disease}!\n"
            f"Expected: {npy_file}"
        )


def precompute_case_control_indices(train_subjects, phenotype_data, disease_labels, rank=0):
    """
    Efficiently identify case and control indices using vectorized operations
    
    Args:
        train_subjects: List of subject tuples
        phenotype_data: DataFrame with phenotype information
        disease_labels: List of disease label column names
        rank: Process rank for distributed training (default 0)
    
    Returns:
        case_indices: List of indices where subject has ≥1 disease
        control_indices: List of indices where subject has 0 diseases
    """
    if rank == 0:
        print("Pre-computing case/control indices (one-time operation)...")
    start_time = time.time()
    
    # Create a mapping dataframe for fast lookup
    train_df = pd.DataFrame(train_subjects, columns=['ID_1', 'ID_2'])
    train_df['idx'] = range(len(train_subjects))
    
    # Ensure ID types match
    train_df['ID_1'] = train_df['ID_1'].astype(str)
    train_df['ID_2'] = train_df['ID_2'].astype(str)
    phenotype_data_copy = phenotype_data.copy()
    phenotype_data_copy['ID_1'] = phenotype_data_copy['ID_1'].astype(str)
    phenotype_data_copy['ID_2'] = phenotype_data_copy['ID_2'].astype(str)
    
    # Merge with phenotype data
    merged = train_df.merge(
        phenotype_data_copy[['ID_1', 'ID_2'] + disease_labels],
        on=['ID_1', 'ID_2'],
        how='left'
    )
    
    # Compute sum of diseases for each subject
    merged['disease_sum'] = merged[disease_labels].sum(axis=1)
    
    # Identify cases and controls
    case_indices = merged[merged['disease_sum'] > 0]['idx'].tolist()
    control_indices = merged[merged['disease_sum'] == 0]['idx'].tolist()
    
    elapsed = time.time() - start_time
    if rank == 0:
        print(f"Pre-computation completed in {elapsed:.2f} seconds")
        print(f"  Cases (≥1 disease): {len(case_indices):,}")
        print(f"  Controls (0 diseases): {len(control_indices):,}")
        print(f"  Ratio: 1:{len(control_indices)/max(1, len(case_indices)):.1f}")
    
    return case_indices, control_indices

def get_sample_files_for_subject(id1, id2, base_path=BASE_PATH):
    """Get all 22 chromosome files for a given subject"""
    sample_files = {}
    
    for chr_num in range(1, 23):  # Chromosomes 1-22
        chr_dir = os.path.join(base_path, f"chr{chr_num}")
        file_pattern = f"sample_{id1}_{id2}_chr{chr_num}.npy"
        file_path = os.path.join(chr_dir, file_pattern)
        
        if not os.path.exists(file_path):
            print(f"Warning: Missing file for subject {id1}_{id2}, chr{chr_num}: {file_path}")
            return None
        
        sample_files[chr_num] = file_path
    
    return sample_files


def discover_all_subjects(base_path=BASE_PATH):
    """Discover all subjects that have complete data across all 22 chromosomes"""
    print("Discovering subjects with complete chromosome data...")
    
    chr1_dir = os.path.join(base_path, "chr1")
    chr1_files = glob.glob(os.path.join(chr1_dir, "sample_*_chr1.npy"))
    
    print(f"Found {len(chr1_files)} files in chr1 directory")
    
    subjects_with_complete_data = []
    
    for chr1_file in chr1_files:
        # Extract ID_1 and ID_2 from filename
        basename = os.path.basename(chr1_file)
        # Format: sample_ID1_ID2_chr1.npy
        parts = basename.replace("sample_", "").replace("_chr1.npy", "").split("_")
        
        if len(parts) == 2:
            id1, id2 = parts[0], parts[1]
            
            # Check if all 22 chromosomes exist for this subject
            sample_files = get_sample_files_for_subject(id1, id2, base_path)
            
            if sample_files is not None:
                subjects_with_complete_data.append((id1, id2))
    
    print(f"Found {len(subjects_with_complete_data)} subjects with complete data (all 22 chromosomes)")
    return subjects_with_complete_data


def load_genotype_data_for_subject(id1, id2, disease_for_snp_filter=None, 
                                   return_shapes=False, 
                                   base_path=BASE_PATH,
                                   gwas_filtered_path=GWAS_FILTERED_SNPS_PATH,
                                   rank=0):
    """
    Load and concatenate genotype data from all 22 chromosomes for a subject
    WITH OPTIONAL GWAS DISEASE-SPECIFIC FILTERING
    
    Args:
        id1: First ID
        id2: Second ID
        disease_for_snp_filter: Disease key for GWAS filtering (OPTIONAL)
                               't2d', 'prostate', 'breast', 'colon', 'pancreatic'
                               If None, loads ALL SNPs without filtering
        return_shapes: If True, return chromosome shapes for debugging
        base_path: Base path for genotype files
        gwas_filtered_path: Base path for GWAS filtered indices
        rank: Process rank for distributed training (default 0)
    
    Returns:
        Concatenated genotype array of shape (total_snps, 3)
        If return_shapes=True, also returns list of (original_shape, filtered_shape) per chromosome
    """
    sample_files = get_sample_files_for_subject(id1, id2, base_path)
    
    if sample_files is None:
        raise ValueError(f"Cannot load data for subject {id1}_{id2}: missing chromosome files")
    
    chromosome_data = []
    chromosome_shapes = []
    
    for chr_num in range(1, 23):
        file_path = sample_files[chr_num]
        
        # Load uint8 data
        chr_data = np.load(file_path)  # Shape: (n_snps_chr, 3)
        original_shape = chr_data.shape
        
        # Apply GWAS disease-specific filtering if requested
        if disease_for_snp_filter is not None:
            # Load prefiltered indices (cached after first load)
            filter_indices = load_gwas_filtered_indices(
                chr_num, 
                disease=disease_for_snp_filter,
                gwas_filtered_path=gwas_filtered_path,
                rank=rank
            )
            
            # Filter the data to keep only GWAS-matched SNPs
            chr_data = chr_data[filter_indices, :]
            filtered_shape = chr_data.shape
            
            if return_shapes:
                chromosome_shapes.append((original_shape, filtered_shape))
        else:
            # No filtering - use all SNPs
            if return_shapes:
                chromosome_shapes.append((original_shape, original_shape))
        
        # Convert uint8 to float32
        chr_data = chr_data.astype(np.float32) / 255.0
        chromosome_data.append(chr_data)
    
    # Concatenate all chromosomes along SNP dimension
    genotype_data = np.concatenate(chromosome_data, axis=0)  # Shape: (total_snps, 3)
    
    if return_shapes:
        return genotype_data, chromosome_shapes
    else:
        return genotype_data


def get_input_size_from_subject(id1, id2, disease_for_snp_filter=None, 
                                base_path=BASE_PATH,
                                gwas_filtered_path=GWAS_FILTERED_SNPS_PATH):
    """
    Get the total number of SNPs for a subject (with optional GWAS filtering)
    
    Args:
        id1: First ID
        id2: Second ID
        disease_for_snp_filter: Disease key for GWAS filtering (OPTIONAL)
                               If None, returns count of ALL SNPs
        base_path: Base path for genotype files
        gwas_filtered_path: Base path for GWAS filtered indices
    
    Returns:
        Total number of SNPs across all chromosomes (filtered or unfiltered)
    """
    genotype_data, shapes = load_genotype_data_for_subject(
        id1, id2, 
        disease_for_snp_filter=disease_for_snp_filter,
        return_shapes=True,
        base_path=base_path,
        gwas_filtered_path=gwas_filtered_path
    )
    total_snps = genotype_data.shape[0]
    
    if disease_for_snp_filter is not None:
        print(f"\nSNP counts per chromosome for subject {id1}_{id2} (GWAS-filtered, disease={disease_for_snp_filter}):")
    else:
        print(f"\nSNP counts per chromosome for subject {id1}_{id2} (NO FILTERING - all SNPs):")
    
    total_original = 0
    total_filtered = 0
    for chr_num, (orig_shape, filt_shape) in enumerate(shapes, 1):
        total_original += orig_shape[0]
        total_filtered += filt_shape[0]
        
        if disease_for_snp_filter is not None:
            pct_kept = 100 * filt_shape[0] / orig_shape[0] if orig_shape[0] > 0 else 0
            print(f"  Chr {chr_num}: {orig_shape[0]:,} → {filt_shape[0]:,} SNPs ({pct_kept:.1f}% kept)")
        else:
            print(f"  Chr {chr_num}: {orig_shape[0]:,} SNPs")
    
    if disease_for_snp_filter is not None:
        print(f"\n  Total (Original): {total_original:,} SNPs")
        print(f"  Total (GWAS-Filtered): {total_filtered:,} SNPs")
        print(f"  Overall: {100*total_filtered/total_original:.1f}% SNPs retained")
    else:
        for chr_num, shape in enumerate(shapes, 1):
            print(f"  Chr {chr_num}: {shape[0]:,} SNPs")
        print(f"\n  Total: {total_snps:,} SNPs (unfiltered)")
    
    return total_snps


class CovariateNormalizer:
    """Normalizer for covariates (Age, BMI, PCs, etc.)"""
    def __init__(self, method="standard"):
        self.method = method
        self.scaler = None
        
        if method == "standard":
            self.scaler = StandardScaler()
        elif method == "minmax":
            self.scaler = MinMaxScaler()
        elif method == "robust":
            self.scaler = RobustScaler()
        elif method == "quantile":
            self.scaler = QuantileTransformer(output_distribution='normal')
        elif method == "power":
            self.scaler = PowerTransformer(method='yeo-johnson')   

    def fit(self, data):
        if self.method != "none" and data is not None and self.scaler is not None:
            if len(data.shape) == 1:
                data = data.reshape(-1, 1)
            self.scaler.fit(data)
    
    def transform(self, data):
        if self.method != "none" and data is not None and self.scaler is not None:
            if len(data.shape) == 1:
                data = data.reshape(-1, 1)
            return self.scaler.transform(data)
        return data


# ROTATION-BASED CONTROL SUBSAMPLING

class RotatingControlSampler:
    """
    Rotates through control samples across epochs while keeping all cases.
    Designed for severe class imbalance in multi-label disease prediction.
    """
    
    def __init__(self, case_subject_indices, control_subject_indices, 
                 target_ratio=5, n_rotations=None, random_state=42, rank=0):
        """
        Args:
            case_subject_indices: List of indices for case subjects
            control_subject_indices: List of indices for control subjects
            target_ratio: Desired controls:cases ratio
            n_rotations: Number of control subsets (auto-calculated if None)
            random_state: Random seed
            rank: Process rank for distributed training
        """
        self.case_indices = np.array(case_subject_indices)
        self.control_indices = np.array(control_subject_indices)
        self.target_ratio = target_ratio
        self.random_state = random_state
        self.rank = rank
        
        # Calculate controls needed per epoch
        self.n_cases = len(self.case_indices)
        self.controls_per_epoch = int(self.n_cases * target_ratio)
        
        # Calculate number of rotations needed to cover all controls
        self.n_controls = len(self.control_indices)
        
        if n_rotations is None:
            self.n_rotations = max(1, int(np.ceil(self.n_controls / self.controls_per_epoch)))
        else:
            self.n_rotations = n_rotations
        
        # Shuffle controls and split into rotation groups
        np.random.seed(random_state)
        shuffled_controls = np.random.permutation(self.control_indices)
        
        # Split into rotation groups
        self.control_groups = []
        for i in range(self.n_rotations):
            start_idx = i * self.controls_per_epoch
            end_idx = min((i + 1) * self.controls_per_epoch, self.n_controls)
            self.control_groups.append(shuffled_controls[start_idx:end_idx])
        
        # Convert to numpy arrays
        self.control_groups = [np.array(group) for group in self.control_groups]
        
        if rank == 0:
            print(f"\n{'='*80}")
            print("ROTATION-BASED CONTROL SAMPLER INITIALIZED")
            print(f"{'='*80}")
            print(f"  Total cases (≥1 disease): {self.n_cases:,}")
            print(f"  Total controls (0 diseases): {self.n_controls:,}")
            print(f"  Original imbalance ratio: 1:{self.n_controls/self.n_cases:.1f}")
            print(f"  Target ratio per epoch: 1:{target_ratio}")
            print(f"  Controls per epoch: {self.controls_per_epoch:,}")
            print(f"  Number of rotations: {self.n_rotations}")
            print(f"  Controls per rotation: {[len(g) for g in self.control_groups]}")
            print(f"  All {self.n_controls:,} controls will be used over {self.n_rotations} epochs")
            print(f"{'='*80}\n")
    
    def get_epoch_indices(self, epoch):
        """Get subject indices for a specific epoch"""
        rotation_idx = epoch % self.n_rotations

        # All cases + current rotation's controls
        epoch_controls = self.control_groups[rotation_idx]
        epoch_indices = np.concatenate([self.case_indices, epoch_controls])
        
        # Shuffle within epoch for random batch composition
        np.random.shuffle(epoch_indices)
        
        return epoch_indices
    
    def get_rotation_info(self, epoch):
        """Get information about current rotation"""
        rotation_idx = epoch % self.n_rotations
        cycle_num = epoch // self.n_rotations
        epoch_in_cycle = (epoch % self.n_rotations) + 1
        
        return {
            'epoch': epoch,
            'rotation_idx': rotation_idx,
            'rotation_num': rotation_idx + 1,
            'total_rotations': self.n_rotations,
            'cycle_num': cycle_num,
            'epoch_in_cycle': epoch_in_cycle,
            'n_controls_in_rotation': len(self.control_groups[rotation_idx]),
            'n_cases': self.n_cases,
            'total_samples': self.n_cases + len(self.control_groups[rotation_idx]),
            'ratio': f"1:{len(self.control_groups[rotation_idx])/self.n_cases:.1f}"
        }
    
    def print_rotation_info(self, epoch):
        """Print formatted rotation information"""
        if self.rank == 0:
            info = self.get_rotation_info(epoch)
            print(f"\n{'─'*80}")
            print(f"EPOCH {info['epoch']} | Rotation {info['rotation_num']}/{info['total_rotations']} "
                  f"| Cycle {info['cycle_num']} | Epoch in Cycle: {info['epoch_in_cycle']}")
            print(f"  Samples: {info['n_cases']:,} cases + {info['n_controls_in_rotation']:,} controls "
                  f"= {info['total_samples']:,} total")
            print(f"  Ratio: {info['ratio']}")
            print(f"{'─'*80}")


class MultilabelGenotypeDataset(Dataset):
    """
    Dataset for chromosome-wise GWAS data with multi-label disease prediction
    WITH DISEASE-SPECIFIC GWAS FILTERING
    """
    
    def __init__(self, subject_list, phenotype_data, disease_labels, 
                 disease_for_snp_filter=None,
                 use_covariates=True, use_age=True, use_gender=True, use_bmi=True,
                 norm_age="standard", norm_pcs="standard", norm_gender="none", norm_bmi="standard",
                 fit_normalizers=True, normalizers=None,
                 base_path=BASE_PATH,
                 gwas_filtered_path=GWAS_FILTERED_SNPS_PATH,
                 rank=0):
        """
        Args:
            subject_list: List of tuples [(id1, id2), ...]
            phenotype_data: DataFrame with phenotype information
            disease_labels: List of disease column names to predict
            disease_for_snp_filter: Disease key for GWAS filtering (OPTIONAL)
                                   't2d', 'prostate', 'breast', 'colon', 'pancreatic'
                                   If None, loads ALL SNPs without filtering
            use_covariates/use_age/use_gender/use_bmi: Which covariates to include
            norm_age/norm_pcs/norm_gender/norm_bmi: Normalization methods
            fit_normalizers: Whether to fit normalizers
            normalizers: Pre-fitted normalizers
            base_path: Base path for genotype files
            gwas_filtered_path: Base path for GWAS filtered indices
            rank: Process rank for distributed training
        """
        self.subject_list = subject_list
        self.phenotype_data = phenotype_data
        self.disease_labels = disease_labels
        self.disease_for_snp_filter = disease_for_snp_filter
        self.use_covariates = use_covariates
        self.use_age = use_age
        self.use_gender = use_gender
        self.use_bmi = use_bmi
        self.base_path = base_path
        self.gwas_filtered_path = gwas_filtered_path
        self.rank = rank
        
        # Validate disease (if specified)
        if disease_for_snp_filter is not None and disease_for_snp_filter not in AVAILABLE_GWAS_DISEASES:
            raise ValueError(
                f"Invalid disease '{disease_for_snp_filter}'. "
                f"Available diseases: {AVAILABLE_GWAS_DISEASES}"
            )
        
        # Create subject ID to phenotype mapping
        self.phenotype_data['subject_key'] = (
            self.phenotype_data['ID_1'].astype(str) + '_' + 
            self.phenotype_data['ID_2'].astype(str)
        )
        self.pheno_dict = self.phenotype_data.set_index('subject_key').to_dict('index')
        
        # Initialize normalizers
        if normalizers is not None:
            # Use pre-fitted normalizers (test set)
            self.age_normalizer = normalizers.get('age')
            self.pc_normalizer = normalizers.get('pc')
            self.gender_normalizer = normalizers.get('gender')
            self.bmi_normalizer = normalizers.get('bmi')
        else:
            # Create new normalizers
            self.age_normalizer = CovariateNormalizer(norm_age) if use_age else None
            self.pc_normalizer = CovariateNormalizer(norm_pcs) if use_covariates else None
            self.gender_normalizer = CovariateNormalizer(norm_gender) if use_gender else None
            self.bmi_normalizer = CovariateNormalizer(norm_bmi) if use_bmi else None
            
            if fit_normalizers:
                self._fit_normalizers()
        
        # Calculate covariate dimension
        self.covariate_dim = 0
        if use_covariates:
            self.covariate_dim += 6  # 6 PCs
        if use_age:
            self.covariate_dim += 1
        if use_gender:
            self.covariate_dim += 1
        if use_bmi:
            self.covariate_dim += 1
        
        print(f"Dataset initialized with {len(self.subject_list)} subjects")
        print(f"  Disease labels: {disease_labels}")
        if disease_for_snp_filter is not None:
            print(f"  GWAS SNP filtering: {disease_for_snp_filter}")
        else:
            print(f"  SNP filtering: None (loading all SNPs)")
        print(f"  Covariate dimension: {self.covariate_dim}")
        print(f"  Using: PCs={use_covariates}, Age={use_age}, Gender={use_gender}, BMI={use_bmi}")
    
    def _fit_normalizers(self):
        """Fit normalizers on the training data"""
        print("Fitting normalizers on training data...")
        
        # Collect covariate data
        age_data = []
        pc_data = []
        gender_data = []
        bmi_data = []
        
        for id1, id2 in self.subject_list:
            subject_key = f"{id1}_{id2}"
            if subject_key in self.pheno_dict:
                pheno = self.pheno_dict[subject_key]
                
                if self.use_age and 'age' in pheno:
                    age_data.append(pheno['age'])
                
                if self.use_covariates:
                    pcs = [pheno.get(f'PC{i}', 0.0) for i in range(1, 7)]
                    pc_data.append(pcs)
                
                if self.use_gender and 'gender' in pheno:
                    gender_data.append(pheno['gender'])
                
                if self.use_bmi and 'BMI' in pheno:
                    bmi_data.append(pheno['BMI'])
        
        # Fit normalizers
        if self.age_normalizer and len(age_data) > 0:
            self.age_normalizer.fit(np.array(age_data))
        
        if self.pc_normalizer and len(pc_data) > 0:
            self.pc_normalizer.fit(np.array(pc_data))
        
        if self.gender_normalizer and len(gender_data) > 0:
            self.gender_normalizer.fit(np.array(gender_data))
        
        if self.bmi_normalizer and len(bmi_data) > 0:
            self.bmi_normalizer.fit(np.array(bmi_data))
        
        print("Normalizers fitted successfully")
    
    def get_normalizers(self):
        """Return fitted normalizers for use in test set"""
        return {
            'age': self.age_normalizer,
            'pc': self.pc_normalizer,
            'gender': self.gender_normalizer,
            'bmi': self.bmi_normalizer
        }
    
    def __len__(self):
        return len(self.subject_list)
    
    def __getitem__(self, idx):
        """Get a single sample"""
        id1, id2 = self.subject_list[idx]
        subject_key = f"{id1}_{id2}"
        
        # Get phenotype data
        if subject_key not in self.pheno_dict:
            raise ValueError(f"Subject {subject_key} not found in phenotype data")
        
        pheno = self.pheno_dict[subject_key]
        
        # Extract disease labels
        labels = [pheno.get(disease, 0) for disease in self.disease_labels]
        
        # Extract and normalize covariates
        covariates = []
        
        if self.use_covariates:
            pcs = np.array([pheno.get(f'PC{i}', 0.0) for i in range(1, 7)]).reshape(1, -1)
            if self.pc_normalizer:
                pcs = self.pc_normalizer.transform(pcs)
            covariates.extend(pcs.flatten())
        
        if self.use_age:
            age = np.array([pheno.get('age', 0.0)]).reshape(1, -1)
            if self.age_normalizer:
                age = self.age_normalizer.transform(age)
            covariates.extend(age.flatten())
        
        if self.use_gender:
            gender = np.array([pheno.get('gender', 0.0)]).reshape(1, -1)
            if self.gender_normalizer:
                gender = self.gender_normalizer.transform(gender)
            covariates.extend(gender.flatten())
        
        if self.use_bmi:
            bmi = np.array([pheno.get('BMI', 0.0)]).reshape(1, -1)
            if self.bmi_normalizer:
                bmi = self.bmi_normalizer.transform(bmi)
            covariates.extend(bmi.flatten())
        
        covariates_tensor = torch.tensor(covariates, dtype=torch.float32)
        
        # Load genotype data with GWAS disease-specific filtering
        genotype_data = load_genotype_data_for_subject(
            id1, id2,
            disease_for_snp_filter=self.disease_for_snp_filter,
            return_shapes=False,
            base_path=self.base_path,
            gwas_filtered_path=self.gwas_filtered_path,
            rank=self.rank
        )
        genotype_tensor = torch.from_numpy(genotype_data).float()
        
        labels_tensor = torch.tensor(labels, dtype=torch.float32)

        return genotype_tensor, covariates_tensor, labels_tensor


def prepare_data_splits(disease_labels,
                       disease_for_snp_filter=None,
                       phenotype_file=PHENOTYPE_FILE, 
                       base_path=BASE_PATH,
                       gwas_filtered_path=GWAS_FILTERED_SNPS_PATH,
                       test_size=0.2, 
                       random_state=42, 
                       rank=0,
                       use_rotation=False):
    """
    Prepare train/test splits for the dataset
    
    Args:
        disease_labels: List of disease column names
        disease_for_snp_filter: Disease for GWAS filtering (OPTIONAL)
                               't2d', 'prostate', 'breast', 'colon', 'pancreatic'
                               If None, calculates input size for all SNPs
        phenotype_file: Path to phenotype file
        base_path: Base path for genotype files
        gwas_filtered_path: Base path for GWAS filtered indices
        test_size: Fraction for testing
        random_state: Random seed
        rank: Process rank
    
    Returns:
        train_subjects, test_subjects, phenotype_data, input_size
    """
    if rank == 0:
        print("=" * 80)
        print("PREPARING DATA SPLITS")
        print("=" * 80)
    
    # Load phenotype data
    if rank == 0:
        print(f"\nLoading phenotype data from: {phenotype_file}")
    phenotype_data = pd.read_csv(phenotype_file, sep='\t')
    if rank == 0:
        print(f"Phenotype data loaded, shape: {phenotype_data.shape}")
        print(f"Columns: {list(phenotype_data.columns)}")
    
    # Check for NaNs in phenotype data
    if rank == 0:
        print("\nChecking for NaNs in phenotype data:")
    covariate_columns = ['age', 'gender', 'BMI'] + [f'PC{i}' for i in range(1, 7)]
    
    for column in covariate_columns:
        if column in phenotype_data.columns:
            nan_count = phenotype_data[column].isna().sum()
            if rank == 0:
                print(f"Column '{column}': {nan_count} NaN values ({nan_count/len(phenotype_data):.2%})")
            
            # If NaNs exist, fill them
            if nan_count > 0:
                if column == 'gender':
                    # For categorical, use mode
                    fill_value = phenotype_data[column].mode()[0]
                else:
                    # For numerical, use mean
                    fill_value = phenotype_data[column].mean()
                
                if rank == 0:
                    print(f"  Filling NaNs with {fill_value}")
                phenotype_data[column] = phenotype_data[column].fillna(fill_value)
    
    # Discover all subjects with complete chromosome data (silently on non-rank-0)
    if rank == 0:
        all_subjects = discover_all_subjects(base_path)
    else:
        import sys, os
        old_stdout = sys.stdout
        sys.stdout = open(os.devnull, 'w')
        try:
            all_subjects = discover_all_subjects(base_path)
        finally:
            sys.stdout = old_stdout
    
    if len(all_subjects) == 0:
        raise ValueError("No subjects found with complete chromosome data!")
    
    # Filter subjects to only those present in phenotype data
    phenotype_ids = set(phenotype_data['ID_1'].astype(str).unique())
    
    filtered_subjects = []
    for id1, id2 in all_subjects:
        if str(id1) in phenotype_ids:
            filtered_subjects.append((id1, id2))
    
    if rank == 0:
        print(f"\nSubjects with both genotype and phenotype data: {len(filtered_subjects)}")
    
    if len(filtered_subjects) == 0:
        raise ValueError("No subjects have both genotype and phenotype data!")
    
    # STRATIFICATION LOGIC
    is_multilabel = len(disease_labels) > 1
    stratify_labels = None

    if not use_rotation:
        stratify_labels = []

        for id1, id2 in filtered_subjects:
            pheno = phenotype_data.loc[
                (phenotype_data["ID_1"].astype(str) == str(id1)) &
                (phenotype_data["ID_2"].astype(str) == str(id2))
            ]

            if len(pheno) == 0:
                stratify_labels.append(0)
                continue

            if is_multilabel:
                # CASE vs CONTROL
                disease_sum = pheno[disease_labels].values.sum()
                stratify_labels.append(int(disease_sum > 0))
            else:
                # SINGLE LABEL
                stratify_labels.append(int(pheno[disease_labels[0]].values[0]))

        stratify_labels = np.asarray(stratify_labels)

        if rank == 0:
            print("\nStratified split enabled:")
            print(
                "  Mode:",
                "multi-label (case/control)" if is_multilabel else "single-label"
            )
            print(f"  Positive rate: {stratify_labels.mean():.4f}")

    # Split subjects into train/test
    train_subjects, test_subjects = train_test_split(
        filtered_subjects, 
        test_size=test_size, 
        random_state=random_state,
        stratify=stratify_labels
    )

    if rank == 0 and stratify_labels is not None:
        def rate(subs):
            idx = [filtered_subjects.index(s) for s in subs]
            return stratify_labels[idx].mean()

        print(f"\nCase/positive rate check:")
        print(f"  Train: {rate(train_subjects):.4f}")
        print(f"  Test : {rate(test_subjects):.4f}")
    
    if rank == 0:
        print(f"\nData split: Train {len(train_subjects)}, Test {len(test_subjects)}")
    
    # Calculate input size from first training subject
    if len(train_subjects) > 0:
        first_subject = train_subjects[0]
        input_size = get_input_size_from_subject(
            first_subject[0],
            first_subject[1],
            disease_for_snp_filter=disease_for_snp_filter,
            base_path=base_path,
            gwas_filtered_path=gwas_filtered_path
        )
        
        if rank == 0:
            if disease_for_snp_filter is not None:
                print(f"\nInput size (GWAS-filtered, disease={disease_for_snp_filter}): {input_size:,}")
            else:
                print(f"\nInput size (unfiltered): {input_size:,}")
    else:
        raise ValueError("No training subjects available to determine input size!")
    
    return train_subjects, test_subjects, phenotype_data, input_size


def create_dataloaders_with_rotation(train_subjects, test_subjects, phenotype_data, disease_labels,
                                     disease_for_snp_filter=None,
                                     batch_size=5, num_workers=2,
                                     use_covariates=True, use_age=True, use_gender=True, use_bmi=True,
                                     norm_age="standard", norm_pcs="standard", norm_gender="none", norm_bmi="standard",
                                     use_rotation=True, target_ratio=5, epoch=0, rank=0,
                                     base_path=BASE_PATH,
                                     gwas_filtered_path=GWAS_FILTERED_SNPS_PATH):
    """
    Create training and test dataloaders WITH ROTATION AND OPTIONAL GWAS FILTERING
    
    Args:
        train_subjects: List of training subject tuples
        test_subjects: List of test subject tuples
        phenotype_data: DataFrame with phenotype data
        disease_labels: List of disease column names
        disease_for_snp_filter: Disease for GWAS filtering (OPTIONAL)
                               't2d', 'prostate', 'breast', 'colon', 'pancreatic'
                               If None, loads ALL SNPs without filtering
        batch_size: Batch size
        num_workers: Number of worker processes
        use_covariates/use_age/use_gender/use_bmi: Which covariates to include
        norm_age/norm_pcs/norm_gender/norm_bmi: Normalization methods
        use_rotation: Whether to use rotation-based sampling
        target_ratio: Target controls:cases ratio
        epoch: Current epoch number for rotation
        rank: Process rank
        base_path: Base path for genotype files
        gwas_filtered_path: Base path for GWAS filtered indices
    
    Returns:
        Dictionary with 'train' and 'test' DataLoaders, rotation_info (or None)
    """
    if rank == 0:
        print("\n" + "=" * 80)
        print("CREATING DATASETS AND DATALOADERS")
        print("=" * 80)
        if disease_for_snp_filter is not None:
            print(f"SNP Filtering: GWAS-based, disease={disease_for_snp_filter}")
        else:
            print(f"SNP Filtering: None (loading all SNPs)")
    
    # Create full training dataset to fit normalizers
    full_train_dataset = MultilabelGenotypeDataset(
        train_subjects, 
        phenotype_data, 
        disease_labels,
        disease_for_snp_filter=disease_for_snp_filter,
        use_covariates=use_covariates,
        use_age=use_age,
        use_gender=use_gender,
        use_bmi=use_bmi,
        norm_age=norm_age,
        norm_pcs=norm_pcs,
        norm_gender=norm_gender,
        norm_bmi=norm_bmi,
        fit_normalizers=True,
        normalizers=None,
        base_path=base_path,
        gwas_filtered_path=gwas_filtered_path,
        rank=rank
    )
    
    # Get fitted normalizers
    fitted_normalizers = full_train_dataset.get_normalizers()
    
    # If using rotation, identify cases and controls
    if use_rotation:
        # Pre-compute case/control indices ONCE and cache
        if not hasattr(create_dataloaders_with_rotation, '_case_control_cache'):
            if rank == 0:
                print("\n" + "="*80)
                print("First epoch: Computing case/control classification")
                print("="*80)
            
            case_indices, control_indices = precompute_case_control_indices(
                train_subjects, phenotype_data, disease_labels, rank=rank
            )
            
            # Cache the results
            create_dataloaders_with_rotation._case_control_cache = {
                'case_indices': case_indices,
                'control_indices': control_indices
            }
        else:
            if rank == 0:
                print("\nUsing cached case/control indices")
            case_indices = create_dataloaders_with_rotation._case_control_cache['case_indices']
            control_indices = create_dataloaders_with_rotation._case_control_cache['control_indices']
        
        if rank == 0:
            print(f"\nMulti-label class distribution:")
            print(f"  Cases (≥1 disease): {len(case_indices):,}")
            print(f"  Controls (0 diseases): {len(control_indices):,}")
            print(f"  Original ratio: 1:{len(control_indices)/max(1, len(case_indices)):.1f}")
        
        # Create or use existing rotation sampler
        if not hasattr(create_dataloaders_with_rotation, '_rotation_sampler'):
            create_dataloaders_with_rotation._rotation_sampler = RotatingControlSampler(
                case_subject_indices=case_indices,
                control_subject_indices=control_indices,
                target_ratio=target_ratio,
                n_rotations=None,
                random_state=42,
                rank=rank
            )
        
        sampler = create_dataloaders_with_rotation._rotation_sampler
        
        # Get indices for this epoch
        epoch_indices = sampler.get_epoch_indices(epoch)
        rotation_info = sampler.get_rotation_info(epoch)
        sampler.print_rotation_info(epoch)
        
        # Create subset of train_subjects for this epoch
        epoch_train_subjects = [train_subjects[i] for i in epoch_indices]
        
        # Create epoch-specific dataset
        train_dataset = MultilabelGenotypeDataset(
            epoch_train_subjects, 
            phenotype_data, 
            disease_labels,
            disease_for_snp_filter=disease_for_snp_filter,
            use_covariates=use_covariates,
            use_age=use_age,
            use_gender=use_gender,
            use_bmi=use_bmi,
            norm_age=norm_age,
            norm_pcs=norm_pcs,
            norm_gender=norm_gender,
            norm_bmi=norm_bmi,
            fit_normalizers=False,
            normalizers=fitted_normalizers,
            base_path=base_path,
            gwas_filtered_path=gwas_filtered_path,
            rank=rank
        )
    else:
        # No rotation - use all training data
        train_dataset = full_train_dataset
        rotation_info = None
    
    # Create test dataset using fitted normalizers (NEVER rotate test set)
    test_dataset = MultilabelGenotypeDataset(
        test_subjects,
        phenotype_data, 
        disease_labels,
        disease_for_snp_filter=disease_for_snp_filter,
        use_covariates=use_covariates,
        use_age=use_age,
        use_gender=use_gender,
        use_bmi=use_bmi,
        norm_age=norm_age,
        norm_pcs=norm_pcs,
        norm_gender=norm_gender,
        norm_bmi=norm_bmi,
        fit_normalizers=False,
        normalizers=fitted_normalizers,
        base_path=base_path,
        gwas_filtered_path=gwas_filtered_path,
        rank=rank
    )
    
    # Create dataloaders with optimizations
    if rank == 0:
        print("\nCreating DataLoaders...")
    dataloaders = {
        'train': DataLoader(
            train_dataset, 
            batch_size=batch_size, 
            shuffle=True, 
            num_workers=num_workers, 
            pin_memory=True, 
            prefetch_factor=1, 
            persistent_workers=True
        ),
        'test': DataLoader(
            test_dataset, 
            batch_size=batch_size, 
            shuffle=False,
            num_workers=num_workers, 
            pin_memory=True, 
            prefetch_factor=1, 
            persistent_workers=True
        )
    }
    
    if rank == 0:
        print("DataLoaders created successfully")
        print(f"- Train batches: {len(dataloaders['train'])}")
        print(f"- Test batches: {len(dataloaders['test'])}")
    
    return dataloaders, rotation_info


# Backward compatibility - original function without rotation
def create_dataloaders(train_subjects, test_subjects, phenotype_data, disease_labels,
                       disease_for_snp_filter=None,
                       batch_size=5, num_workers=2,
                       use_covariates=True, use_age=True, use_gender=True, use_bmi=True,
                       norm_age="standard", norm_pcs="standard", norm_gender="none", norm_bmi="standard",
                       base_path=BASE_PATH,
                       gwas_filtered_path=GWAS_FILTERED_SNPS_PATH,
                       rank=0):
    """
    Original create_dataloaders function (without rotation)
    Kept for backward compatibility
    WITH OPTIONAL GWAS DISEASE-SPECIFIC FILTERING
    
    Args:
        train_subjects: List of training subject tuples
        test_subjects: List of test subject tuples
        phenotype_data: DataFrame with phenotype data
        disease_labels: List of disease column names
        disease_for_snp_filter: Disease for GWAS filtering (OPTIONAL)
                               't2d', 'prostate', 'breast', 'colon', 'pancreatic'
                               If None, loads ALL SNPs without filtering
        batch_size: Batch size
        num_workers: Number of worker processes
        use_covariates/use_age/use_gender/use_bmi: Which covariates to include
        norm_age/norm_pcs/norm_gender/norm_bmi: Normalization methods
        base_path: Base path for genotype files
        gwas_filtered_path: Base path for GWAS filtered indices
        rank: Process rank
    
    Returns:
        Dictionary with 'train' and 'test' DataLoaders, None (for consistency)
    """
    dataloaders, _ = create_dataloaders_with_rotation(
        train_subjects, test_subjects, phenotype_data, disease_labels,
        disease_for_snp_filter=disease_for_snp_filter,
        batch_size=batch_size, num_workers=num_workers,
        use_covariates=use_covariates, use_age=use_age, use_gender=use_gender, use_bmi=use_bmi,
        norm_age=norm_age, norm_pcs=norm_pcs, norm_gender=norm_gender, norm_bmi=norm_bmi,
        use_rotation=False, target_ratio=5, epoch=0, rank=rank,
        base_path=base_path,
        gwas_filtered_path=gwas_filtered_path
    )
    return dataloaders, None


# Example usage
if __name__ == "__main__":
    print("Testing dataloader with GWAS disease-specific filtering...")
    
    # Disease labels based on new phenotype file columns
    disease_labels = ['PrC', 'PanC', 'CRC', 'BC', 'T2D']
    
    # Prepare data splits with T2D filtering
    train_subjects, test_subjects, phenotype_data, input_size = prepare_data_splits(
        disease_labels=disease_labels,
        disease_for_snp_filter='t2d',  # T2D filtering
        phenotype_file=PHENOTYPE_FILE,
        test_size=0.2,
        random_state=42
    )
    
    print(f"\nInput size (T2D GWAS-filtered): {input_size:,}")
    
    # Test with T2D-specific GWAS filtering
    print("\n\n" + "="*80)
    print("TESTING WITH T2D-SPECIFIC GWAS FILTERING")
    print("="*80)
    
    # Create dataloaders with rotation
    dataloaders, rotation_info = create_dataloaders_with_rotation(
        train_subjects=train_subjects,
        test_subjects=test_subjects,
        phenotype_data=phenotype_data,
        disease_labels=disease_labels,
        disease_for_snp_filter='t2d',  # REQUIRED parameter
        batch_size=2,
        num_workers=2,
        use_covariates=True,
        use_age=True,
        use_gender=True,
        use_bmi=True,
        norm_age="standard",
        norm_pcs="standard",
        norm_gender="none",
        norm_bmi="standard",
        use_rotation=True,
        target_ratio=5,
        epoch=0
    )
    
    # Test loading a batch
    print("\nTesting batch loading...")
    train_loader = dataloaders['train']
    for batch_idx, (genotypes, covariates, labels) in enumerate(train_loader):
        print(f"\nBatch {batch_idx + 1}:")
        print(f"  Genotypes shape: {genotypes.shape}")
        print(f"  Covariates shape: {covariates.shape}")
        print(f"  Labels shape: {labels.shape}")
        
        if batch_idx == 0:
            break
    
    print("\n" + "=" * 80)
    print("TEST COMPLETED SUCCESSFULLY!")
    print("=" * 80)
    
    # Test with no filtering (load all SNPs)
    print("\n\n" + "="*80)
    print("TESTING WITH NO FILTERING (ALL SNPs)")
    print("="*80)
    
    input_size_unfiltered = get_input_size_from_subject(
        first_subject[0],
        first_subject[1],
        disease_for_snp_filter=None  # No filtering
    )
    
    print(f"\nInput size (unfiltered): {input_size_unfiltered:,}")
    
    dataloaders_unfiltered, _ = create_dataloaders_with_rotation(
        train_subjects=train_subjects,
        test_subjects=test_subjects,
        phenotype_data=phenotype_data,
        disease_labels=disease_labels,
        disease_for_snp_filter=None,  # No filtering - load all SNPs
        batch_size=2,
        num_workers=2,
        use_rotation=True,
        target_ratio=5,
        epoch=0
    )
    
    # Test loading a batch
    print("\nTesting batch loading (unfiltered)...")
    train_loader = dataloaders_unfiltered['train']
    for batch_idx, (genotypes, covariates, labels) in enumerate(train_loader):
        print(f"\nBatch {batch_idx + 1}:")
        print(f"  Genotypes shape: {genotypes.shape}")
        print(f"  Covariates shape: {covariates.shape}")
        print(f"  Labels shape: {labels.shape}")
        
        if batch_idx == 0:
            break
    
    # Test backward compatibility function (without rotation)
    print("\n\n" + "="*80)
    print("TESTING BACKWARD COMPATIBILITY (WITHOUT ROTATION)")
    print("="*80)
    
    dataloaders_no_rotation, _ = create_dataloaders(
        train_subjects=train_subjects,
        test_subjects=test_subjects,
        phenotype_data=phenotype_data,
        disease_labels=disease_labels,
        disease_for_snp_filter='t2d',  # With filtering
        batch_size=2,
        num_workers=2
    )
    
    print(f"\nDataloaders created (no rotation):")
    print(f"  Train batches: {len(dataloaders_no_rotation['train'])}")
    print(f"  Test batches: {len(dataloaders_no_rotation['test'])}")
    
    print("\n" + "=" * 80)
    print("ALL TESTS COMPLETED SUCCESSFULLY!")
    print("=" * 80)